### ISSUE TITLE
[Umbrella]  Release 0.8.0

### ISSUE THREAD

**Issue by jerqi** [apache/incubator-uniffle#1029]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues) and found no similar issues.

### Describe the proposal

Release Apache Uniffle 0.8.0, we would like to release binary package. There are many things to do. First, we should ensure what issues should be included in this version.

### Task list

- [x] Bump `master` to `0.9.0-SNAPSHOT`.
- [x] Checkout `branch-0.8`.
- [x] Tag and release `0.8.0-rc1`.
    - [x] Backport necessary fixes from `master` to `branch-0.8`.
    - [x] Bump project version to `0.8.0` in `branch-0.8`.
    - [x] (GitHub) Tag `0.8.0-rc1`.
    - [x] (SVN) Upload tarball, checksum and signature to `.../0.8.0-rc1/`.
    - [x] Post release note on [Uniffle website][1].
    - [x] Vote on dev@uniffle.apache.org
    - [ ] Vote on general@incubator.apache.org
- [x] Tag and release `0.8.0-rc2` (optional).
    - [x] Cancel the `0.8.0-rc1` vote on corresponding mailing lists.
    - [x] Backport necessary fixes from `master` to `branch-0.8`.
    - [x] (GitHub) Tag `0.8.0-rc2`.
    - [x] (SVN) Upload tarball, checksum and signature to `.../0.8.0-rc2/`.
    - [x] Update release note on [Uniffle website][1].
    - [x] Vote on dev@uniffle.apache.org
    - [ ] Vote on general@incubator.apache.org
- [x] Tag and release `0.8.0-rc3` (optional).
    - [x] Cancel the `0.8.0-rc2` vote on corresponding mailing lists.
    - [x] Backport necessary fixes from `master` to `branch-0.8`.
    - [x] (GitHub) Tag `0.8.0-rc3`.
    - [x] (SVN) Upload tarball, checksum and signature to `.../0.8.0-rc3/`.
    - [x] Update release note on [Uniffle website][1].
    - [x] Vote on dev@uniffle.apache.org
    - [x] Vote on general@incubator.apache.org
- [x] Tag and release `0.8.0`.
    - [x] (SVN) Move the artifacts under `dev/.../0.8.0-rc?` to `release/.../0.8.0` (by PPMC).
    - [x] (GitHub) Tag `0.8.0` to `0.8.0-rc?` and upload the artifacts.
    - [x] Update download link on [Uniffle website][1].
    - [x] Bump project version to `0.8.1-SNAPSHOT` in `branch-0.8`
    - [x] Post an announcement on general@incubator.apache.org

[1]: https://github.com/apache/incubator-uniffle-website

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
I hope the issues can be included in this version.
https://github.com/apache/incubator-uniffle/issues/586
https://github.com/apache/incubator-uniffle/issues/1013
https://github.com/apache/incubator-uniffle/issues/1011

**Comment by zuston** [comment]
I think we'd better to have a benchmark report of grpc and netty before 0.8 releasing.

**Comment by jerqi** [comment]
@xianjingfeng Let's start to release 0.8.0 version.

**Comment by xianjingfeng** [comment]
> @xianjingfeng All prs are ready. Let's start to release 0.8.0 version.

OK, i am going to start working on this today.
