### ISSUE TITLE
[Umbrella] Netty replace Grpc on data transfer

### ISSUE THREAD

**Issue by jerqi** [apache/incubator-uniffle#133]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues) and found no similar issues.

### Describe the proposal
When we use Grpc, we find that our bottleneck is on Grpc, Grpc brings the cost of data copy and data serialization. We must encounter GC problems when we use Grpc. We should use Netty replace Grpc on data transfer and use off heap memory to reduce GC time.

### Task list

- [x] #582
- [x] #583
- [x] #584
- [x] #585 
- [x] #586 
- [ ] #587 
- [x] #590
- [ ] #591 
- [x] #592 
- [ ] #593
- [x] #596
- [x] #597
- [ ] #639 
- [x] #640
- [x] #711
- [x] #719 
- [x] #720
- [x] #804
### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
Could we use grpc zero-copy to solve this problem? Alluxio also use Grpc to transfer data, I think the problem we encountered also exist in Alluxio

**Comment by jerqi** [comment]
> Could we use grpc zero-copy to solve this problem?
> 
> By the way, Alluxio also use Grpc to transfer data, I think the problem we encountered also exist in Alluxio. We could refer https://dzone.com/articles/moving-from-apache-thrift-to-grpc-a-perspective-fr?utm_medium=tumblr&utm_source=dlvr.it&utm_campaign=Feed%3A%20dzone%2Fintegration

It seems that it use protobuf to serialize the data.

**Comment by zuston** [comment]
I dont look through the full design of GRPC zero-copy design and Alluxio's implementation. 
Maybe we could do the POC to test the performance compared with the netty implementation. Overall, it looks easy to extend the zero-copy by GRPC, like this https://github.com/GoogleCloudPlatform/grpc-gcp-java/pull/77

From my perspective, GRPC is the general and cross-language, that means it make possible to implement the shuffle-server by other languages like rust to avoid GC and obtain better memory management in the future.

**Comment by jerqi** [comment]
We have had a POC code about Netty. It will improve 10% performance for Uniffle.

**Comment by zuston** [comment]
> We have had a POC code about Netty. It will improve 10% performance for Uniffle.

Sounds great! If I have time, I will do a zero-copy POC to compare with netty.

**Comment by zuston** [comment]
After applying the POC of netty, will the problem of #230 exist? @jerqi

**Comment by leixm** [comment]
What is the progress of this proposal, maybe I can join the development?

**Comment by jerqi** [comment]
> What is the progress of this proposal, maybe I can join the development?

We only have some POC code. I don't have much time, if you like , I can assign this issue to you. And I can provide our POC code to you.

**Comment by zuston** [comment]
> > What is the progress of this proposal, maybe I can join the development?
> 
> We only have some POC code. I don't have much time, if you like , I can assign this issue to you. And I can provide our POC code to you.

+1. Could u help make this POC code to another branch.

**Comment by jerqi** [comment]
This poc is based on Uber RSS netty implement, it's better that we can compare the Ali's rss netty implement, Uber's rss netty implement and other RSS netty implement.

**Comment by leixm** [comment]
Thank you.

**Comment by leixm** [comment]
> Commit ID: [4463b80](https://github.com/apache/incubator-uniffle/commit/4463b80deacbcd47ddc151f8d7750d1e5f035077) git apply patch1 [netty1.txt](https://github.com/apache/incubator-uniffle/files/9839621/netty1.txt)
> 
> git apply patch2 [netty2.txt](https://github.com/apache/incubator-uniffle/files/9839628/netty2.txt)
> 
> After apply the patches, we can get the code https://github.com/jerqi/incubator-uniffle/tree/netty_poc
> 
> According the poc test, we can get 10% performance improvement.

Thank you.

**Comment by jerqi** [comment]
@leixm  @zuston Do you want to discuss this issue through a meeting? I will start a meeting to discuss the issue #80, I want to discuss this issue, too. There are some other issues which we need to discuss, so I will send a email to our dev mail list, and select a proper date to start the meeting. You can tell me what time you are free by the email.

**Comment by leixm** [comment]
> @leixm @zuston Do you want to discuss this issue through a meeting? I will start a meeting to discuss the issue #80, I want to discuss this issue, too. There are some other issues which we need to discuss, so I will send a email to our dev mail list, and select a proper date to start the meeting. You can tell me what time you are free by the email.

Let's discuss it.

**Comment by zuston** [comment]
> > @leixm @zuston Do you want to discuss this issue through a meeting? I will start a meeting to discuss the issue #80, I want to discuss this issue, too. There are some other issues which we need to discuss, so I will send a email to our dev mail list, and select a proper date to start the meeting. You can tell me what time you are free by the email.
> 
> Let's discuss it.

+1. Could we have a discussion in this week?

**Comment by jerqi** [comment]
@leixm I have already send an email https://lists.apache.org/thread/2jlm3fswmsxy619ldyo4px700p3ybnvc. Do you have time at 11 am (UTC +8) Thursday this week?

**Comment by leixm** [comment]
Yes, I'm free at this time.

**Comment by jerqi** [comment]
> Yes, I'm free at this time.

Meeting link is https://meeting.tencent.com/dm/oR95wASCNe91

**Comment by jerqi** [comment]
Offline Discussion Result:
We will compare the rpc frameworks of other rss, and @leixm will give a design doc. Next step, we will make the shuffle server will off heap as possible as we can.

**Comment by leixm** [comment]
https://docs.google.com/document/d/1srlBlLpJ3hbzd8ru5QaY5aCSLR9M2ttHXmlvcFC-SLg/edit?usp=sharing @jerqi  @zuston  @smallzhongfeng  @smallzhongfeng  Can you help review this design.

**Comment by leixm** [comment]
Currently, we use Uniffle version 0.6.0 internally. When there are tasks running, the GC of Shuffle Server will take up to 40% of the cpu time, and FullGC will appear occasionally.

**Comment by jerqi** [comment]
@leixm Could you give us the authority of the comment for your design doc?

**Comment by jerqi** [comment]
Thanks @leixm There are some questions.
1. Do you have a POC test? Could you attach test result?
2. Do you compare with other plans, such as Uber, Alibaba RSS, Bytedance RSS. Could we reuse their plan?
3. Do our client need off heap memory to read the data from the server?

**Comment by leixm** [comment]
1.I did some POC tests, which can significantly reduce GCTime, I will sort out and upload some test results later
2.I made some comparisons. The design we propose is similar to Alibaba RSS. Do you have a better suggestion? I tried to do some tests on each RSS, but I found it difficult to do a specific performance comparison
3.read buffer refers to the memory usage of ShuffleServer, not the client

**Comment by leixm** [comment]
These RSS have one thing in common, using off-heap memory, their GC time is significantly smaller than Uniffle.

**Comment by jerqi** [comment]
> 1.I did some POC tests, which can significantly reduce GCTime, I will sort out and upload some test results later 2.I made some comparisons. The design we propose is similar to Alibaba RSS. Do you have a better suggestion? I tried to do some tests on each RSS, but I found it difficult to do a specific performance comparison 3.read buffer refers to the memory usage of ShuffleServer, not the client

Could we have analysis about the every RSS's network transfer? How about poc code which I provide? Do they have the same performance?

**Comment by leixm** [comment]
> @leixm Could you give us the authority of the comment for your design doc?

done, Can you comment now?

**Comment by leixm** [comment]
> > 1.I did some POC tests, which can significantly reduce GCTime, I will sort out and upload some test results later 2.I made some comparisons. The design we propose is similar to Alibaba RSS. Do you have a better suggestion? I tried to do some tests on each RSS, but I found it difficult to do a specific performance comparison 3.read buffer refers to the memory usage of ShuffleServer, not the client
> 
> Could we have analysis about the every RSS's network transfer? How about poc code which I provide? Do they have the same performance?

Any suggestions to measure the performance precisely?

**Comment by leixm** [comment]
I think we can evaluate whether the performance has improved in two parts. The first part is GC time, which is relatively simple. You can evaluate it by viewing the process through the running time of the app and jstat. The second part is whether serialization/deserialization has improved , this is more complicated. At present, what I think of is to evaluate through transportTime, which includes the serialization/deserialization time of the client, the network transmission time, and the serialization/deserialization time of ShuffleServer

**Comment by jerqi** [comment]
> > > 1.I did some POC tests, which can significantly reduce GCTime, I will sort out and upload some test results later 2.I made some comparisons. The design we propose is similar to Alibaba RSS. Do you have a better suggestion? I tried to do some tests on each RSS, but I found it difficult to do a specific performance comparison 3.read buffer refers to the memory usage of ShuffleServer, not the client
> > 
> > 
> > Could we have analysis about the every RSS's network transfer? How about poc code which I provide? Do they have the same performance?
> 
> Any suggestions to measure the performance precisely?

I don't know whether micro benchmark can solve this problem. GC time can only be evaluted when we use several jobs to verify them.

**Comment by jerqi** [comment]
> > @leixm Could you give us the authority of the comment for your design doc?
> 
> done, Can you comment now?

Yes.

**Comment by leixm** [comment]
cc@jerqi  I've included some test data in the design doc, including uniffle, celeborn, bytedance css, uber rss.

**Comment by jerqi** [comment]
> cc@jerqi I've included some test data in the design doc, including uniffle, celeborn, bytedance css, uber rss.

If we can prove the Celeborn have better performance than Uber RSS. We can continue this our design. We also need to consider that we need use offheap memory to compress/decompress data.

**Comment by leixm** [comment]
@advancedxy  @jerqi  I have uploaded a POC code, which is helpful to alleviate the problem of FullGC, but many places still need to be optimized. https://github.com/leixm/incubator-uniffle/tree/netty_poc_2

**Comment by leixm** [comment]
> addressed

It is still in the development process and has not been applied to the production environment.

**Comment by leixm** [comment]
> Hi, @leixm xianming, has this issue already been addressed in your internal prod env? Do you any ETA for the PR to be uploaded?
It is still in the development process and has not been applied to the production environment.

**Comment by leixm** [comment]
Can I add some ISSUE? Let's get involved. @jerqi

**Comment by leixm** [comment]
Can I add some ISSUE? Let's get involved. @jerqi

**Comment by jerqi** [comment]
> Can I add some ISSUE? Let's get involved. @jerqi

Yes, you can.

**Comment by jerqi** [comment]
After offline discussion, we should involve more people to participate in this issue. @zuston @leixm @advancedxy @kaijchen @smallzhongfeng @xianjingfeng  Maybe we should have a regular meeting to discuss this issue continuously. WDYT?

**Comment by xianjingfeng** [comment]
> After offline discussion, we should involve more people to participate in this issue. @zuston @leixm @advancedxy @kaijchen @smallzhongfeng @xianjingfeng Maybe we should have a regular meeting to discuss this issue continuously. WDYT?

It is ok for me.

**Comment by Gustfh** [comment]
recently, we also working on this feature, since we found the problem is on the grpc, later we will share our result about this poc.  

+1 for the regular meeting

**Comment by smallzhongfeng** [comment]
> After offline discussion, we should involve more people to participate in this issue. @zuston @leixm @advancedxy @kaijchen @smallzhongfeng @xianjingfeng Maybe we should have a regular meeting to discuss this issue continuously. WDYT?

It is ok for me.

**Comment by kaijchen** [comment]
Let's create a new branch such as `netty` for this feature. So we can collaborate on it before it's ready to be merged into master.

**Comment by leixm** [comment]
> After offline discussion, we should involve more people to participate in this issue. @zuston @leixm @advancedxy @kaijchen @smallzhongfeng @xianjingfeng Maybe we should have a regular meeting to discuss this issue continuously. WDYT?

It is ok for me.

**Comment by zuston** [comment]
> After offline discussion, we should involve more people to participate in this issue. @zuston @leixm @advancedxy @kaijchen @smallzhongfeng @xianjingfeng Maybe we should have a regular meeting to discuss this issue continuously. WDYT?

+1. Looking forward this.

**Comment by leixm** [comment]
> > https://github.com/leixm/incubator-uniffle/tree/netty_poc_2
> 
> Great. Do you think is it possible to submit an WIP pr now?
> 
> > It is still in the development process and has not been applied to the production environment.
> 
> No problem, let's create issues/prs targets your branch and discuss more.

Should we submit WIP PR first or do a performance test first to prove that the code is valid, then submit WIP PR and continue to complete the code.

**Comment by jerqi** [comment]
1. @leixm If we use Netty, we can transfer local file with `sendfile` that a zero copy linux api. We can remove read memory. 
It's an important improvement.
2. And maybe we need some benchmark tests. We could set up our benchmark test systems. @LuciferYang Do you give us some advice about benchmark tests? 
3. Reader and writer also need to support to use off heap memory to compress and decompress data.

**Comment by leixm** [comment]
Good idea, but the current performance bottleneck is mainly in ShuffleServer, we can improve the throughput of ShuffleServer first.

**Comment by jerqi** [comment]
> Good idea, but the current performance bottleneck is mainly in ShuffleServer, we can improve the throughput of ShuffleServer first.

You misunderstand me. When shuffle server read the local file, we use `sendfile` api to improve our shuffle server performance.

**Comment by leixm** [comment]
You are right.

> > Good idea, but the current performance bottleneck is mainly in ShuffleServer, we can improve the throughput of ShuffleServer first.
> 
> You misunderstand me. When shuffle server read the local file, we use `sendfile` api to improve our shuffle server performance.
you are right.

**Comment by leixm** [comment]
> > Good idea, but the current performance bottleneck is mainly in ShuffleServer, we can improve the throughput of ShuffleServer first.
> 
> You misunderstand me. When shuffle server read the local file, we use `sendfile` api to improve our shuffle server performance.

You are right.

**Comment by leixm** [comment]
> 1. @leixm If we use Netty, we can transfer local file with `sendfile` that a zero copy linux api. We can remove read memory.
>    It's an important improvement.
> 2. And maybe we need some benchmark tests. We could set up our benchmark test systems. @LuciferYang Do you give us some advice about benchmark tests?
> 3. Reader and writer also need to support to use off heap memory to compress and decompress data.

These ideas are very good, we can raise issues.

**Comment by jerqi** [comment]
@leixm Have you do some performance tests? 
@advancedxy @Gustfh @smallzhongfeng @zuston @leixm @kaijchen How about every wednesday 10:15 am every week for this issue regular meeting?

**Comment by leixm** [comment]
I am doing some tests on the throughput performance of ShuffleServer, but the comparison results are not very good. I found that the performance of ShuffleServer has a lot to do with the disk write performance, and it needs to be better when the disk throughput performance is greater than the ShuffleServer throughput performance. Verify whether the throughput performance of ShuffleServer has improved.

**Comment by leixm** [comment]
> @leixm Have you do some performance tests? @advancedxy @Gustfh @smallzhongfeng @zuston @leixm @kaijchen How about every wednesday 10:15 am every week for this issue regular meeting?

It's ok for me.

**Comment by leixm** [comment]
@jerqi  Or do you have a better test method to accurately verify the throughput performance of ShuffleServer?

**Comment by leixm** [comment]
Or we can write some test codes. After ShuffleServer receives the data, it does not perform disk writing operations, and verifies the throughput performance of ShuffleServer in the scenario where the impact of disk writing is excluded.

**Comment by jerqi** [comment]
The performance of disk is limited. Every HDD is 100MB/s. Every SDD is 1GB/s.
Usually we test this with 1TB tpcds and 1TB Terasort. If we can get performance improve, we can merge some prs first.

**Comment by leixm** [comment]
> The performance of disk is limited. Every HDD is 100MB/s. Every SDD is 1GB/s. Usually we test this with 1TB tpcds and 1TB Terasort. If we can get performance improve, we can merge some prs first.

How many ShuffleServer nodes were there in the previous test?

**Comment by jerqi** [comment]
> > The performance of disk is limited. Every HDD is 100MB/s. Every SDD is 1GB/s. Usually we test this with 1TB tpcds and 1TB Terasort. If we can get performance improve, we can merge some prs first.
> 
> How many ShuffleServer nodes were there in the previous test?

3 - 6 nodes.

**Comment by leixm** [comment]
I will do tpcds test to verify the performance.

**Comment by jerqi** [comment]
@leixm  I think we can submit some small prs to our master branch first.

**Comment by leixm** [comment]
okay.

**Comment by jerqi** [comment]
Meeting link https://meeting.tencent.com/dm/nVx6mxO8vIrc

**Comment by zuston** [comment]
I have some questions regarding the memory management of the shuffle server in the Netty implementation. Specifically, I'm curious about how we store shuffle data in memory. Do we use Netty's ByteBuf or a customized memory pool managed by Uniffle?

Based on my reading of the design document, there are two memory sections allocated for network and shuffle data storage. Would it be accurate to describe them as shared buffers?

I believe that introducing a customized memory pool could potentially address the above issues. Furthermore, this could also benefit the transfer of shuffle data using GRPC.

cc @leixm @advancedxy @jerqi

**Comment by zuston** [comment]
> I believe we should do it in baby steps, the netty rpc framework should be introduced first, then the off-heap memory management, then unified memory management and spill. 

Yes. Let's reserve this 

> I haven't thought it throughly, but I believe we can learn from the best.

https://github.com/flink-extended/flink-remote-shuffle is a good example

**Comment by jerqi** [comment]
> > I believe we should do it in baby steps, the netty rpc framework should be introduced first, then the off-heap memory management, then unified memory management and spill.
> 
> Yes. Let's reserve this
> 
> > I haven't thought it throughly, but I believe we can learn from the best.
> 
> https://github.com/flink-extended/flink-remote-shuffle is a good example

If you think it's worth doing, you should set up an issue to track it.

**Comment by connorlwilkes** [comment]
How far off is this umbrella feature? I would be interested in taking a look at it as I have faced problems relating to large GC when running large shuffle jobs

**Comment by jerqi** [comment]
> How far off is this umbrella feature? I would be interested in taking a look at it as I have faced problems relating to large GC when running large shuffle jobs.

Only two prs. But we should fix some issues. Maybe we can finish this feature at the end of June. What's your company? Do you use Uniffle in the production environment?

**Comment by jerqi** [comment]
> How far off is this umbrella feature? I would be interested in taking a look at it as I have faced problems relating to large GC when running large shuffle jobs

Maybe this is helpful for you. https://github.com/apache/incubator-uniffle/issues/674#issuecomment-1454611218
