### ISSUE TITLE
[Umbrella] Release 0.9.0

### ISSUE THREAD

**Issue by EnricoMi** [apache/incubator-uniffle#1654]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues) and found no similar issues.

### Describe the proposal

Release Apache Uniffle 0.9.0, we would like to release binary package. There are many things to do. First, we should ensure what issues should be included in this version.

### Task list

- [x] #1655
- [x] Checkout `branch-0.9`.
- [x] Tag and release `v0.9.0-rc1`.
    - [x] Backport necessary fixes from `master` to `branch-0.9`.
        - [x] https://github.com/apache/incubator-uniffle/milestone/2
    - [x] Bump project version to `0.9.0` in `branch-0.9`.
    - [x] (GitHub) Tag `v0.9.0-rc1`:
        - https://github.com/apache/incubator-uniffle/releases/tag/v0.9.0-rc1
    - [x] (SVN) Upload tarball, checksum and signature to `.../0.9.0-rc1/`:
        - https://dist.apache.org/repos/dist/dev/incubator/uniffle/0.9.0-rc1/
- [X] Tag and release `v0.9.0-rc2`.
    - [x] (GitHub) Tag `v0.9.0-rc2`:
        - https://github.com/apache/incubator-uniffle/releases/tag/v0.9.0-rc2
    - [x] (SVN) Upload tarball, checksum and signature to `.../0.9.0-rc2/`:
        - https://dist.apache.org/repos/dist/dev/incubator/uniffle/0.9.0-rc2/
    - [x] Post release note on [Uniffle website][1]:
        - https://github.com/apache/incubator-uniffle-website/pull/75
    - [X] Vote on dev@uniffle.apache.org
    - [X] Vote on general@incubator.apache.org
- [X] Tag and release `0.9.0`.
    - [x] (SVN) Move the artifacts under `dev/.../0.9.0-rc2` to `release/.../0.9.0` (by PPMC).
    - [x] (GitHub) Tag `v0.9.0` to `v0.9.0-rc2` and upload the artifacts.
    - [x] Update download link on [Uniffle website][1]:
      - https://github.com/apache/incubator-uniffle-website/pull/82
    - [X] Bump project version to `0.9.1-SNAPSHOT` in `branch-0.9`:
      - #1907
    - [x] Post an announcement on general@incubator.apache.org

[1]: https://github.com/apache/incubator-uniffle-website

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
@EnricoMi Maybe we could to start to release 0.9.0-rc1.

**Comment by zuston** [comment]
Oh, this is my first time to find the Milestone componet that can be as the tracker for version management. Maybe the 0.10.0 could be created now to track the main features.

**Comment by EnricoMi** [comment]
> Oh, this is my first time to find the Milestone componet that can be as the tracker for version management. Maybe the 0.10.0 could be created now to track the main features.

Please add your favourite issues / pull requests to https://github.com/apache/incubator-uniffle/milestone/3.

**Comment by EnricoMi** [comment]
> @EnricoMi Maybe we could to start to release 0.9.0-rc1.

we are not waiting for #1720?

**Comment by xianjingfeng** [comment]
@EnricoMi @jerqi @zuston Should we wait for #1751

**Comment by xianjingfeng** [comment]
> Let's not wait with the release for more features. There will always be new features. We should rather release more frequently.

But it is not a feature. Version 0.8 already supports gluten.

**Comment by EnricoMi** [comment]
Then this is not an [Improvement] but a [Fix]: https://github.com/apache/incubator-uniffle/issues/1751

**Comment by rickyma** [comment]
@EnricoMi It's been a while. Could you please continue working on this?

**Comment by EnricoMi** [comment]
I'll finish the release on Monday.

**Comment by EnricoMi** [comment]
This has been released.
