### ISSUE TITLE
[Umbrella] Support authentication for some rest interface

### ISSUE THREAD

**Issue by xianjingfeng** [apache/incubator-uniffle#1949]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues) and found no similar issues.

### Describe the proposal

Currently, the rest interfaces donot have authentication. This is unsafe for some rest interfaces, such as some modifying configuration-related interfaces.

### Task list

- [ ] # 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xianjingfeng** [comment]
@yl09099 @rickyma @jerqi PTAL
