### ISSUE TITLE
[Umbrella] Support Tez Client

### ISSUE THREAD

**Issue by baitian77** [apache/incubator-uniffle#321]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Now, uniffle support Spark and MR client，but does not support tez.

### Task list
1. Design document
- [x]  #337
2. Dependent apache-tez code changes & pr
- [x]  #831 
- [x] #832 
3. client-tez common
- [x]  #747
- [x]  #872  
- [x]  #894 
- [x]  #915 
- [x]  #916 
- [x]  #919 
4. client-tez AM
- [x]  #819 
- [x]  #918 
5. client-tez shuffle read
- [x] #854 
- [x] #920 
- [x] #922  
- [x] #929 
- [x] #935 
6. client-tez shuffle write 
- [x]  #855 
- [x]  #930
- [x]   #943  
- [x]   #944 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
Thanks! It's a really great work!

**Comment by zuston** [comment]
Looking forward to this feature!

**Comment by zuston** [comment]
Could we indicate which PR is the first PR ?

**Comment by jerqi** [comment]
cc @BsoBird If you have interest about Tez on rss, you can focus on this issue.

**Comment by jerqi** [comment]
Finished.

**Comment by jerqi** [comment]
@Lobo2008 @microeastcowboy  @XiaoqiMa  Uniffle is a remote shuffle service. Maybe you have interest about MapReduce on Uniffle and Tez on Uniffle.
