### ISSUE TITLE
Introduce the reservedData to support more custom pluggable accessCheckers

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#44]
### Background
In current implementation, DelegationRssShuffleManager could decide whether to use uniffle or sort shuffle service by calling remote coordinator. The pluggable accessCheckers can be extended in coordinator to support more custom requirements.

### Motivation
When we hope the uniffle can be applied to specified spark jobs to control which shuffle service to use, the mechanism of pluggable accessCheckers is useful. 

We can implement the CustomDelegationRssShuffleManager(like `DelegationRssShuffleManager`)to inject some custom accessInfo and remote call the coordinator which use the custom access policy to decide which spark job use the uniffle shuffle service. However the current codebase dont support inject more accessinfo in client, only have `tags` and `accessid`. So this proposal hopes to introduce the data structure to store more custom extensible requirement.

### Goals
1. Support injecting more custom data in AccessClusterRequest, which can be set in client

### Tasks

- [x] https://github.com/apache/incubator-uniffle/pull/42
- [x] https://github.com/apache/incubator-uniffle/pull/43
- [x] https://github.com/apache/incubator-uniffle/pull/41

**Comment by zuston** [comment]
As i know the pluggable access checkers have been supported in current implementation of coordinator, which are managed by AccessManager.

And to support customized acess checker, i hope we can introduce a  general pb message in AccessInfo. Feel free to discuss more. @duanmeng

**Comment by duanmeng** [comment]
>hope we can introduce a general pb message in AccessInfo
We coud add a pb message `AccessInfo` and put it inside the pb message `AccessClusterRequest`. And then make the client can populate these `extraProperties` through spark conf. So that we can inject special access checkers (not part of the code base of uniffle) for business requirements.
```protobuf
message AccessInfo {
  string accessId = 1;
  repeated string tags = 2;
  map<string, string> extraProperties;
}
```

**Comment by zuston** [comment]
All done. Close
