### ISSUE TITLE
[Umbrella] Use SpotBugs to improve code quality

### ISSUE THREAD

**Issue by kaijchen** [apache/incubator-uniffle#532]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues) and found no similar issues.

### Describe the proposal

SpotBugs is a program which uses static analysis to look for bugs in Java code.

SpotBugs checks for more than 400 bug patterns. Bug descriptions can be found [here](https://spotbugs.readthedocs.io/en/latest/bugDescriptions.html)

For example: https://github.com/apache/incubator-uniffle/pull/527

### Task list

* [x] DM_NUMBER_CTOR
* [ ] EI_EXPOSE_REP
* [ ] EI_EXPOSE_REP2
* [ ] EI_EXPOSE_STATIC_REP2
* [ ] IS2_INCONSISTENT_SYNC
* [ ] MS_EXPOSE_REP
* [ ] MS_PKGPROTECT
* [ ] MS_CANNOT_BE_FINAL
* [x] REC_CATCH_EXCEPTION
* [x] RV_RETURN_VALUE_IGNORED_BAD_PRACTICE
* [x] SC_START_IN_CTOR
* [ ] SE_BAD_FIELD
* [ ] SWL_SLEEP_WITH_LOCK_HELD
* [ ] THROWS_METHOD_THROWS_RUNTIMEEXCEPTION
* [ ] THROWS_METHOD_THROWS_CLAUSE_BASIC_EXCEPTION
* [ ] THROWS_METHOD_THROWS_CLAUSE_THROWABLE
* [x] URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD
* [x] UWF_UNWRITTEN_PUBLIC_OR_PROTECTED_FIELD

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!
