### ISSUE TITLE
[Umbrella] Improve CI workflows

### ISSUE THREAD

**Issue by kaijchen** [apache/incubator-uniffle#580]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues) and found no similar issues.

### Describe the proposal

The current CI can be improved in many aspects.
The goal is to make CI cleaner, faster and more informative.

### Task list

- [x] cache maven repositories
- [x] create a standalone workflow for k8s operator
- [ ] standardize profile names, i.e. `-Pspark3` is actually `-Pspark3.1`
- [x] split tests into UT and IT
- [ ] do not repeat common tests (UT)
- [ ] reuse compiled artifacts
- [x] parallel build, i.e. `mvn -T`
- [ ] parallel test, make sure no resources race in tests

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!
