### ISSUE TITLE
[Umbrella] Slow integration tests

### ISSUE THREAD

**Issue by kaijchen** [apache/incubator-uniffle#604]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues) and found no similar issues.

### Describe the proposal

Some integration tests are taking too long to execute, maybe we can improve them by tweaking configuration, reduce the sleep time, or reduce the workload.

### Task list

- [ ] Time elapsed: 48.638 s - in org.apache.uniffle.test.QuorumTest
- [ ] Time elapsed: 74.901 s - in org.apache.uniffle.test.ShuffleWithRssClientTest
- [ ] Time elapsed: 66.122 s - in org.apache.uniffle.test.RepartitionWithLocalFileRssTest
- [ ] Time elapsed: 174.062 s - in org.apache.uniffle.test.RepartitionWithMemoryRssTest
- [ ] Time elapsed: 239.197 s - in org.apache.uniffle.test.WordCountTest
- [ ] Time elapsed: 235.059 s - in org.apache.uniffle.test.SecondarySortTest
- [ ] Time elapsed: 249.674 s - in org.apache.uniffle.test.LargeSorterTest

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
+1. I also doubt whether the mini hdfs startup is the main factor
