### ISSUE TITLE
[Umbrella] Release 0.7.0

### ISSUE THREAD

**Issue by kaijchen** [apache/incubator-uniffle#611]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues) and found no similar issues.

### Describe the proposal

Release Apache Uniffle 0.7.0

### Task list

- [x] Bump `master` to `0.8.0-SNAPSHOT`.
- [x] Checkout `branch-0.7`.
- [ ] Tag and release `0.7.0-rc1`.
    - [x] Backport necessary fixes from `master` to `branch-0.7`.
    - [x] Bump project version to `0.7.0` in `branch-0.7`.
    - [x] (GitHub) Tag `0.7.0-rc1`.
    - [x] (SVN) Upload tarball, checksum and signature to `.../0.7.0-rc1/`.
    - [x] Post release note on [Uniffle website][1].
    - [x] Vote on dev@uniffle.apache.org
    - [ ] Vote on general@incubator.apache.org
- [ ] Tag and release `0.7.0-rc2` (optional).
    - [x] Cancel the `0.7.0-rc1` vote on corresponding mailing lists.
    - [x] Backport necessary fixes from `master` to `branch-0.7`.
    - [x] (GitHub) Tag `0.7.0-rc2`.
    - [x] (SVN) Upload tarball, checksum and signature to `.../0.7.0-rc2/`.
    - [x] Update release note on [Uniffle website][1].
    - [x] Vote on dev@uniffle.apache.org
    - [x] Vote on general@incubator.apache.org
- [ ] Tag and release `0.7.0`.
    - [x] (SVN) Move the artifacts under `dev/.../0.7.0-rc?` to `release/.../0.7.0` (by PPMC).
    - [ ] (GitHub) Tag `0.7.0` to `0.7.0-rc?` and upload the artifacts.
    - [x] Update download link on [Uniffle website][1].
    - [ ] Bump project version to `0.7.1-SNAPSHOT` in `branch-0.7`
    - [ ] Post an announcement on general@incubator.apache.org

[1]: https://github.com/apache/incubator-uniffle-website

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
I don't know why the step of `Bump master to 0.8.0-SNAPSHOT` is the final step ? It looks unrelated with the tag creating

**Comment by kaijchen** [comment]
> I don't know why the step of `Bump master to 0.8.0-SNAPSHOT` is the final step ? It looks unrelated with the tag creating

Make sense, updated.

**Comment by zuston** [comment]
Do we have a release guide? like https://linkis.apache.org/zh-CN/community/how-to-release/

I'm not familiar with Apache release.

**Comment by kaijchen** [comment]
> Do we have a release guide? like https://linkis.apache.org/zh-CN/community/how-to-release/

I don't think there is one yet. You can reference this link, and ask any questions in the current thread.

Cc @jerqi

**Comment by zuston** [comment]
How to deploy my gpg key to uniffle svn? Here: https://dist.apache.org/repos/dist/dev/incubator/uniffle/KEYS @kaijchen .

**Comment by kaijchen** [comment]
> How to deploy my gpg key to uniffle svn? Here: https://dist.apache.org/repos/dist/dev/incubator/uniffle/KEYS

Need help from PPMC, Cc @jerqi.

**Comment by zuston** [comment]
> Need help from PPMC, Cc @jerqi.

OK

Besides, need I do the mvn deploy operation? Or @jerqi

**Comment by kaijchen** [comment]
> Besides, need I do the mvn deploy operation?

AFAIK, no need for now.

**Comment by kaijchen** [comment]
@zuston I've updated the checklist in the issue description.

**Comment by zuston** [comment]
> Hi, what's the status of 0.7.0 release?

I'm working on this.

**Comment by jerqi** [comment]
> I have drafted the release. could you help check this? https://github.com/apache/incubator-uniffle/releases/tag/untagged-e126c5971ca7ac9e1d6d @advancedxy @kaijchen @jerqi

https://github.com/apache/incubator-uniffle/pull/322
https://github.com/apache/incubator-uniffle/pull/307
https://github.com/apache/incubator-uniffle/pull/249
The three prs should be highlighted, too.

**Comment by kaijchen** [comment]
> I have drafted the release. could you help check this? https://github.com/apache/incubator-uniffle/releases/tag/untagged-e126c5971ca7ac9e1d6d @advancedxy @kaijchen @jerqi

Please bump version in `branch-0.7` to `0.7.0`.
Also, it's recommended to push a tag manually.

```bash
git checkout branch-0.7
git tag v0.7.0
git push origin v0.7.0
```

**Comment by zuston** [comment]
> > I have drafted the release. could you help check this? https://github.com/apache/incubator-uniffle/releases/tag/untagged-e126c5971ca7ac9e1d6d @advancedxy @kaijchen @jerqi
> 
> Please bump version in `branch-0.7` to `0.7.0`. Also, it's recommended to push a tag manually.
> 
> ```shell
> git checkout branch-0.7
> git tag v0.7.0
> git push origin v0.7.0
> ```

OK. Do we need to set a rc version? @kaijchen

**Comment by zuston** [comment]
Besides, does the source tarballs need to upload to apache svn before voting this release?

**Comment by kaijchen** [comment]
> OK. Do we need to set a rc version?

No, because if everything goes well, `0.7.0-rc1` will become `0.7.0`.

> Besides, does the source tarballs need to upload to apache svn before voting this release?

Yes, the tarball should be named `apache-uniffle-0.7.0-rc1-incubating-src.tar.gz`.

**Comment by zuston** [comment]
> Yes, the tarball should be named apache-uniffle-0.7.0-rc1-incubating-src.tar.gz.

OK. Could you tell me the steps or commands to build this tarball?

**Comment by kaijchen** [comment]
> Yes, the tarball should be named apache-uniffle-0.7.0-rc1-incubating-src.tar.gz.

Sorry, no `rc1` in tarball name, see https://dist.apache.org/repos/dist/dev/incubator/uniffle/0.6.1-rc2/

**Comment by zuston** [comment]
> > Yes, the tarball should be named apache-uniffle-0.7.0-rc1-incubating-src.tar.gz.
> 
> OK. Could you tell me the steps or commands to build this tarball?

And how to upload this?

**Comment by zuston** [comment]
I heard from @jerqi that we just need to do source release.

**Comment by kaijchen** [comment]
> OK. Could you tell me the steps or commands to build this tarball?

Since we are making source release only, you can use `git-archive` to create the tarball.

> And how to upload this?

Put the tarball, checksum and signature in SVN, and upload it.
See: https://linkis.apache.org/zh-CN/community/how-to-release/#3-%E5%8F%91%E5%B8%83apache-svn%E4%BB%93%E5%BA%93

**Comment by kaijchen** [comment]
You can also refer to https://kvrocks.apache.org/community/create-a-release

**Comment by zuston** [comment]
> Yes, the tarball should be named apache-uniffle-0.7.0-rc1-incubating-src.tar.gz.
Edit:apache-uniffle-0.7.0-incubating-src.tar.gz under 0.7.0-rc1 directory.

Done https://dist.apache.org/repos/dist/dev/incubator/uniffle/

**Comment by kaijchen** [comment]
> Done https://dist.apache.org/repos/dist/dev/incubator/uniffle/

Artifacts looks good, but version should be changed to `0.7.0`.

**Comment by kaijchen** [comment]
> ```shell
> git checkout branch-0.7
> git tag v0.7.0
> git push origin v0.7.0
> ```

Tag should be `v0.7.0-rc1` in this case.

**Comment by jerqi** [comment]
You don't change the pom.xml 's version t0 0.7.0.

**Comment by zuston** [comment]
> You don't change the pom.xml 's version t0 0.7.0.

Got it.

**Comment by zuston** [comment]
> > You don't change the pom.xml 's version t0 0.7.0.
> 
> Got it.

Updated

**Comment by zuston** [comment]
> > I have drafted the release. could you help check this? https://github.com/apache/incubator-uniffle/releases/tag/untagged-e126c5971ca7ac9e1d6d @advancedxy @kaijchen @jerqi
> 
> #322 #307 #249 The three prs should be highlighted, too.

Updated. https://github.com/apache/incubator-uniffle/releases/tag/untagged-b70804300bb45088ec43

**Comment by kaijchen** [comment]
@zuston please refer to the task list in https://github.com/apache/incubator-uniffle/issues/611#issue-1587121237

**Comment by zuston** [comment]
> @zuston please refer to the task list in [#611 (comment)](https://github.com/apache/incubator-uniffle/issues/611#issue-1587121237)

Thanks. I will do remaining tasks tomorrow

**Comment by zuston** [comment]
I have sent the vote email to dev@uniffle.apache.org cc @kaijchen

**Comment by kaijchen** [comment]
> I have sent the vote email to [dev@uniffle.apache.org](mailto:dev@uniffle.apache.org)

Thanks. 

> Comparing to 0.6.1, a bug fix of memory leak is included:

Minor versions are not like patch versions, the changes may be too many to describe in a sentence.
Maybe you can include the link to the (proposed) release note instead when voting in the incubator mailing list.

**Comment by zuston** [comment]
> Minor versions are not like patch versions, the changes may be too many to describe in a sentence.
Maybe you can include the link to the (proposed) release note instead when voting in the incubator mailing list.


It's my fault, I forget changing this.

**Comment by zuston** [comment]
I forgot deleting the pom.xml.versionBackup files, so do I need to cancel this vote and revote the rc-2 version after fixing? @kaijchen

**Comment by kaijchen** [comment]
> I forgot deleting the pom.xml.versionBackup files, so do I need to cancel this vote and revote the rc-2 version after fixing? @kaijchen

Yes, but no need to be hurry. You can give one or two days to let people check for other problems, and fix them together in `rc2`.

**Comment by zuston** [comment]
> @zuston I think it's a good time to fix the problems and release the RC2.

Done. The vote mail has been sent

**Comment by jerqi** [comment]
@zuston Do we need rc3?

**Comment by zuston** [comment]
> @zuston Do we need rc3?

Let's make rc2 as release version directly? WDYT?

**Comment by jerqi** [comment]
> > @zuston Do we need rc3?
> 
> Let's make rc2 as release version directly? WDYT?

We should release rc3, we don't get enough votes because of flaky tests.

**Comment by zuston** [comment]
> We should release rc3, we don't get enough votes because of flaky tests.

OK.

**Comment by jerqi** [comment]
> I have checked the branch-0.7 latest commits, it looks all flaky test fixes are all cherry picked. I want to release 0.7-rc3

Let's release 0.7-rc3.

**Comment by zuston** [comment]
> > I have checked the branch-0.7 latest commits, it looks all flaky test fixes are all cherry picked. I want to release 0.7-rc3
> 
> Let's release 0.7-rc3.

Done

**Comment by zuston** [comment]
Is it time to release 0.7.0 ?

**Comment by kaijchen** [comment]
> Is it time to release 0.7.0 ?

We need to vote on https://lists.apache.org/list.html?general@incubator.apache.org

**Comment by jerqi** [comment]
> Is it time to release 0.7.0 ?

@zuston Remind, we should start to vote in the incubator.

**Comment by zuston** [comment]
All done.

**Comment by jerqi** [comment]
@zuston You forget bump version to 0.7.1-SNAPSHOT in branch-0.7.

**Comment by zuston** [comment]
> @zuston You forget bump version to 0.7.1-SNAPSHOT in branch-0.7.

Done.
