### ISSUE TITLE
[Improvement] Huge partition optimization on local disk

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#695]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

In #378, we have discussed the huge partition problems. And the final solution is to make it flush to HDFS directly and limit memory usage. 

But for some users only using `MEMORY_LOCALFILE` storage type, it's useless. So this issue is to track the huge partition optimization on local disk.

## SubTasks
1. Support flushing single partition to multiple disks
2. Support pluggable local disk selection strategy
3. Support dynamic assignment of shuffle server, especially when the disk of server is full
4. ...

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
We could use more MEMORY_LOCALFILE_HDFS, HDFS have more capacity to process the problems.

**Comment by zuston** [comment]
> We could use more MEMORY_LOCALFILE_HDFS, HDFS have more capacity to process the problems.

Yes, I think so. But users like VIP shop hope this optimization could be applied in local disk. Could you help ping? Let's discuss more.

**Comment by jerqi** [comment]
@xumanbu @Gustfh

**Comment by zuston** [comment]
> > > We could use more MEMORY_LOCALFILE_HDFS, HDFS have more capacity to process the problems.
> > 
> > 
> > Yes, I think so. But users like VIP shop hope this optimization could be applied in local disk. Could you help ping? Let's discuss more.
> 
> use hdfs can solve capacity issues, but hdfs write rate is slower than ssd, the memory will be full quickly in large data written. in my mind if we use hdfs storage,uniffle client should have backpressure to limit client write rate.

Yes, it does. Please see https://github.com/apache/incubator-uniffle/blob/master/docs/server_guide.md#huge-partition-optimization
