### ISSUE TITLE
[Umbrella] Cleanup residue files in tmp directory after tests

### ISSUE THREAD

**Issue by kaijchen** [apache/incubator-uniffle#722]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues) and found no similar issues.

### Describe the proposal

There are many residue files in tmp directory after tests.
Sometimes it will cause issues in repeated tests or parallel tests.
We can use JUnit 5 managed `@TempDir` to replace `Files.createTempDirectory()`.

```console
$ mvn clean package -Pspark3
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  21:06 min
[INFO] Finished at: 2023-03-15T14:36:19+08:00
[INFO] ------------------------------------------------------------------------
$ find | grep '/target/tmp/'
./integration-test/spark-common/target/tmp/dynamicConf5843229430228465171conf
./integration-test/spark-common/target/tmp/rss62430369913332225
./integration-test/spark-common/target/tmp/dynamicConf6147274175500176169conf
./integration-test/spark-common/target/tmp/dynamicConf4208328593701611930conf
./integration-test/spark-common/target/tmp/rss562630552492365514
./integration-test/spark-common/target/tmp/rss46277087768255567
./integration-test/spark-common/target/tmp/dynamicConf1817755823767020171conf
./integration-test/spark-common/target/tmp/rss8341883984735558073
./integration-test/spark-common/target/tmp/dynamicConf8701841393224148370conf
./integration-test/spark-common/target/tmp/rss1030728888778640567
./integration-test/spark-common/target/tmp/dynamicConf5751228400475518214conf
./integration-test/spark-common/target/tmp/dynamicConf919596028861517530conf
./integration-test/spark-common/target/tmp/dynamicConf2112348039475291387conf
./integration-test/spark-common/target/tmp/dynamicConf8968200515884439551conf
./integration-test/spark-common/target/tmp/spark-1b6fb52c-382a-4666-a743-01fe376a9da3
./integration-test/spark-common/target/tmp/dynamicConf3642606138147557145conf
./integration-test/spark-common/target/tmp/dynamicConf7764795188572170812conf
./integration-test/spark-common/target/tmp/rss1340437940162131196
./integration-test/spark3/target/tmp/rssdata4683867891894737544
./integration-test/spark3/target/tmp/rssdata4683867891894737544/local-1678862145522_1678862145477
./integration-test/spark3/target/tmp/rssdata4683867891894737544/local-1678862145522_1678862145477/1
./integration-test/spark3/target/tmp/rssdata4683867891894737544/local-1678862145522_1678862145477/1/92-92
./integration-test/spark3/target/tmp/rssdata4683867891894737544/local-1678862145522_1678862145477/1/92-92/9.134.131.52-20001.data
./integration-test/spark3/target/tmp/rssdata4683867891894737544/local-1678862145522_1678862145477/1/92-92/9.134.131.52-20001.index
...
./integration-test/spark3/target/tmp/rssdata4683867891894737544/local-1678862145522_1678862145477/0/6-6
./integration-test/spark3/target/tmp/rssdata4683867891894737544/local-1678862145522_1678862145477/0/6-6/9.134.131.52-20001.data
./integration-test/spark3/target/tmp/rssdata4683867891894737544/local-1678862145522_1678862145477/0/6-6/9.134.131.52-20001.index
./integration-test/spark3/target/tmp/dynamicConf4726090287767810753conf
./integration-test/spark3/target/tmp/dynamicConf7395142600914379199conf
./integration-test/spark3/target/tmp/dynamicConf5485162686795986256conf
./integration-test/spark3/target/tmp/spark-43b4179d-9940-4625-a2bf-f87bbe86ccbb
./storage/target/tmp/dummy-data-file7618350169586815030.index
./storage/target/tmp/dummy-data-file1719959362551363828.data
./client-spark/spark3/target/tmp/spark-18439b64-6f95-49ed-98b9-46053929202e
./server/target/tmp/removeShuffleDataWithLocalfileTest8262825757764355506
./server/target/tmp/removeShuffleDataWithLocalfileTest8262825757764355506/removeShuffleDataWithLocalfileTest
./server/target/tmp/removeShuffleDataWithLocalfileTest5796962123722765961
./server/target/tmp/removeShuffleDataWithLocalfileTest5796962123722765961/removeShuffleDataWithLocalfileTest
./common/target/tmp/rss3072326445112259054
```

### Task list

- [ ] residue files of unit tests
- [ ] residue files of spark3 integration tests
- [ ] residue files of spark2 integration tests
- [ ] residue files of mr integration tests

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!
