### ISSUE TITLE
[FEATURE] [Subtask] Decommission ShuffleServer through Cli

### ISSUE THREAD

**Issue by slfan1989** [apache/incubator-uniffle#969]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

We will provide a command to decommission the ShuffleServer.

### Motivation

We provide a REST API to support the Decommission of ShuffleServer, it is essential to also support this functionality in the command-line.

### Describe the solution

The cluster administrators can Decommission ShuffleServer using a command.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!
